AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - spring.cloud::reference

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage name for the deployment

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Runtime: java21

Resources:
  SpringBootDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: spring-boot-dependencies
      ContentUri: layers/spring-boot-layer/
      CompatibleRuntimes:
        - java21
      RetentionPolicy: Retain

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ReferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: spring.cloud.StreamLambdaHandler::handleRequest
      CodeUri: .
      Policies: AWSLambdaBasicExecutionRole
      Layers:
        - !Ref SpringBootDependenciesLayer  # Reference the layer
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: live
      Events:
        ProxyResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: any

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Export:
      Name: !Sub "${AWS::StackName}-api-url"